name=W5500Ethernet
version=1.0.0
author=Amir Shahbazi
maintainer=Amir Shahbazi
sentence=W5500 Ethernet library for STM32 (bare-metal and STM32duino)
paragraph=TCP server/client, Modbus TCP, socket management for WIZ550io and W5500 modules
category=Communication
url= https://github.com/Amir13600631/W5500Ethernet
architectures=*
depends=SPI
